### ISSUE TITLE
StateChange block - Allow user to name state signal

### ISSUE THREAD

**Issue by Swilchek** [nio-blocks/state_change#16]
As-is - it appears that the user cannot name the signal coming out of the StateChange block, without using a dynamic field block or some other masking method.

It would be convenient if you could add a text field for the block that would allow the user to create a unique state name.

If possible - allowing the user to add in multiple state expression fields (with their accompanying state name) would be ideal - to avoid the use of multiple blocks on the UI.

**Comment by hansmosh** [comment]
If you want to keep track of multiple states then it is possible to make your state a more complex expression. For example, if you want that state of both `$this` and `$that`. Then you could do a state this: 
```
{{ {"this": $this, "that": $that} }}
```
Now the state will be notified anytime either changes and the `state` will be the whole dictionary of values that you care about.
