### ISSUE TITLE
current_state command should not return an unknown state

### ISSUE THREAD

**Issue by mattdodge** [nio-blocks/state_change#25]
Right now, if you try to get the current state (via the command) of a state the block doesn't know about, it returns the default state. Either we shouldn't do that, or we should provide a way to return all states that the block is aware of. Maybe both...

**Comment by hansmosh** [comment]
@mattdodge Do you think if a state doesn't exist yet then return an empty dictionary in the current_state command?

**Comment by mattdodge** [comment]
I actually think it should return a 404

`GET /service/ServiceName/StateBlock/current_state?group=NOTASTATE` should return 404.

`GET /service/ServiceName/StateBlock/current_state?group=REALSTATE` should return 200 and include the current state

`GET /service/ServiceName/StateBlock/current_state` should return 200 and send back a dictionary of all groups and states

**Comment by hansmosh** [comment]
Ok, I like that. I didn't think to return 404. I'm not sure I know how to do that in a block command. Raise an exception?

**Comment by mattdodge** [comment]
I think (untested) you can do this:
```python
raise nio.modules.web.http.HTTPNotFound
```

**Comment by hansmosh** [comment]
@mattdodge That response is `500 Internal Server Error`. Does that seem ok or do we have another way to return 404?

Also, do we have a way of detecting if a parameter was left blank? Or is the only way to do this to detect if the argument is the default? (And if so, is a good default `None` even though technically that could be a group?)

**Comment by mattdodge** [comment]
1. That does not seem ok, this is a nio bug with the way we execute commands.

2. You would have to detect whether it was the default or not. Using `None` is probably not the best, we should declare another type to use there instead. Similar to what is done in this SO post (http://stackoverflow.com/a/14749388/1222076)

**Comment by mattdodge** [comment]
So for now, let's keep raising the NotFound, once it gets fixed in [nio](http://n.io) the error code will turn from 500 to 404

**Comment by hansmosh** [comment]
In case someone looks at this in the future...

The StringParamater converts any object to a string so that doesn't work for checking if a parameter was not specified. Instead I am using the allow_none flag and checking for that.
