### ISSUE TITLE
Don't process initial state until it is needed

### ISSUE THREAD

**Issue by mattdodge** [nio-blocks/state_change#35]
Rather than computing initial states during block configuration, we should be evaluating the expressions when the signal comes in. This will allow us to do the following things:

- Use attributes on incoming signals to determine initial state
- Use time based expressions in initial state that are tied to when the first signal came through

**Comment by mattdodge** [comment]
@kevincrabbe this is a good one to start with

**Comment by kevincrabbe** [comment]
@mattdodge ; @hansmosh and I are not sure if this change should happen.

**Comment by mattdodge** [comment]
@kevincrabbe ok.... If you're proposing a close and no fix, you'll need to give some more information than that. Is that what you're saying or do you want to discuss it?

**Comment by kevincrabbe** [comment]
What are the use cases for wanting these feature requests? It would be helpful to know the motivation for this feature in order to come up with an implementation. Maybe the use case can be solved through service design as opposed to block implementation.

**Comment by mattdodge** [comment]
@kevincrabbe The use case was something like wanting to use the merge state block to keep track of the last time something was updated or passed through the block. When putting `datetime.datetime.now()` in the initial state it was locking in the time the block was started rather than the time a signal actually went through the block.

**Comment by mattdodge** [comment]
The original use case was needed by @32bitkid a few months back if you want to discuss any further with him

**Comment by kevincrabbe** [comment]
- The change will not be made because the related use cases can be satisfied through service design

-  The read me will be updated to better explain how the 'initial_state' behaves when it is configured as a python expression

- A separate issue has been made to address the problem of knowing if a state has been set or not. #38
